### PR TITLE
Add awx_host_ssl_certificate_key to specify separate private key

### PR DESCRIPTION
**Pull request by clissoni**
Hi,
in our environment is required to have a separate private key.
I've made changes to match the option in awx project git inventory file:
#Optional key file
#ssl_certificate_key=

### CODE REVIEW

**Review by ikke-t — CHANGES_REQUESTED** [review]
How about reducing duplicate lines, and only have the if for the certificate_key line in case of awx_host_ssl_certificate_key is defined? Else the original line. Thus leaving the listen and cert lines as is, not duplicating them?

**Comment by clissoni** [comment]
Hi,
Thank you very much for your time, I've pushed a modified version of nginx.conf.j2 let me know if this is ok for you, I've tested it in our environment and it's working

**Review by ikke-t — COMMENTED** [review]
I believe you still need to revert your change at line 50 of nginx.conf. Now it won't apply if separate key is used. This is extra: 'and (awx_host_ssl_certificate_key is not defined)', and of course the parenthesis.

**Comment by clissoni** [comment]
Yes you're right, on my local version I've changed it but not here, sorry

**Review by ikke-t — APPROVED** [review]
lgtm

**Pull request merged**
