### PR TITLE
AWX 10 Update

### PR DESCRIPTION
**Pull request by Klaas-**
Hi,
I've looked some more into this and added a few of the upstream possibilities (build in ssl, other CAs with mounting host pki). I've also changed some variables to match the ones in docker compose and this includes the change to the sclorg postgresql images.

Migrations run ~10 mins on my system for a fresh install.

Greetings
Klaas

### CODE REVIEW

**Comment by Klaas-** [comment]
I can't seem to get AWX_PROOT_ENABLED working

Error message: `bwrap: capset failed: Operation not permitted`

not sure how that is working in kubernetes :)

**Comment by Klaas-** [comment]
If I add some capabilities:
```
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add: ['SETUID','SETGID','NET_ADMIN','SYS_CHROOT','SYS_ADMIN','SETPCAP','SETFCAP','SYS_PTRACE']
      privileged: true
```
I get a little further :)

`bwrap: pivot_root: Operation not permitted`

for now I'll just leave it disabled

**Comment by ikke-t** [comment]
Pheew, you've done quite job, thanks! Good stuff, I tested it on RHEL8 and it works. As you seem to have changed the variable names, please also update the test file accordingly, and perhaps readme if needed. I didn't check where all they are, but shouldn't be biggie.

Sorry I've been busy doing other stuff recently (http://fevermap.net) , I haven't really checked on this project. You had another PR also open, is it all included in this one too, or should I pull it separately?

**Comment by Klaas-** [comment]
This includes the change to psql10 sclorg container.

I couldn't get a migration path for existing installs though.

**Comment by Klaas-** [comment]
I think we should get this into the awx installer, https://github.com/ansible/awx/issues/3998 - I'll see if I can get an opinion from one of the awx guys

**Pull request merged**
